#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
  path: /logout
  methods: GET

index:
    path: /
    controller: App\Controller\MainController::index

main:
    path: /main
    controller: App\Controller\MainController::index
